###
POST http://localhost:8000/transitymap/us-central1/fetchArticles HTTP/1.1
Content-Type: application/json

{
  "responseId": "2b2f5819-730c-4366-928b-278b5c2e0a1a",
  "queryResult": {
    "parameters": {
      "topic": "Docker",
      "date": ""
    },
    "allRequiredParamsPresent": true,
    "fulfillmentMessages": [
      {
        "text": {
          "text": [
            ""
          ]
        }
      }
    ],
    "intent": {
      "name": "projects/transitymap/agent/intents/ba388a41-2466-4324-925b-8a447b3bc85b",
      "displayName": "Topic Intent"
    },
    "intentDetectionConfidence": 1,
    "diagnosticInfo": {},
    "languageCode": "en"
  },
  "originalDetectIntentRequest": {
    "payload": {}
  },
  "session": "projects/transitymap/agent/sessions/17803378-a68b-ff12-6044-360a34d9fd44"
}